# Generated by Django 5.2.13 on 2026-04-22 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('avg_pace', models.FloatField(default=0, help_text='平均配速 min/km')),
                ('preferred_terrain', models.CharField(blank=True, default='', max_length=200)),
                ('injury_history', models.JSONField(blank=True, default=list)),
                ('route_preferences', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'user_profile',
            },
        ),
        migrations.CreateModel(
            name='RouteRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, max_length=64)),
                ('name', models.CharField(blank=True, default='', max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('route_geojson', models.JSONField(blank=True, default=dict)),
                ('distance_km', models.FloatField(default=0)),
                ('elevation_gain', models.FloatField(default=0)),
                ('shade_ratio', models.FloatField(default=0)),
                ('terrain_types', models.JSONField(blank=True, default=list)),
                ('water_stations', models.JSONField(blank=True, default=list)),
                ('scenic_points', models.JSONField(blank=True, default=list)),
                ('suitability_score', models.FloatField(default=0)),
                ('ai_commentary', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes', to='core.userprofile')),
            ],
            options={
                'db_table': 'route_record',
            },
        ),
        migrations.CreateModel(
            name='ConversationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, max_length=64)),
                ('role', models.CharField(max_length=20)),
                ('content', models.TextField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='core.userprofile')),
            ],
            options={
                'db_table': 'conversation_history',
                'ordering': ['created_at'],
            },
        ),
    ]
