# Generated by Django 5.2.13 on 2026-04-19 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScenicViewpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('view_type', models.CharField(choices=[('sea_view', '海景'), ('mountain_view', '山景'), ('city_view', '城市景观'), ('sunset', '日落观景'), ('lighthouse', '灯塔')], max_length=50)),
                ('lng', models.FloatField()),
                ('lat', models.FloatField()),
                ('description', models.TextField(blank=True)),
                ('view_angle_start', models.FloatField(default=0, help_text='视线起始角度')),
                ('view_angle_end', models.FloatField(default=360, help_text='视线结束角度')),
                ('elevation', models.FloatField(default=0)),
                ('district', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'gis_scenic_viewpoint',
            },
        ),
        migrations.CreateModel(
            name='GreenCoverage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grid_id', models.CharField(max_length=20, unique=True)),
                ('center_lng', models.FloatField()),
                ('center_lat', models.FloatField()),
                ('ndvi_value', models.FloatField(default=0, help_text='NDVI植被指数 -1到1')),
                ('shade_level', models.IntegerField(default=0, help_text='遮荫等级 0-5')),
                ('district', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'gis_green_coverage',
                'indexes': [models.Index(fields=['center_lng', 'center_lat'], name='gis_green_c_center__7d8159_idx')],
            },
        ),
        migrations.CreateModel(
            name='POI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amap_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('poi_type', models.CharField(choices=[('water_station', '饮水站/便利店'), ('scenic_point', '观景点'), ('park', '公园'), ('sports_facility', '运动设施'), ('toilet', '公共厠所'), ('parking', '停车场')], max_length=50)),
                ('amap_type_code', models.CharField(blank=True, max_length=100)),
                ('lng', models.FloatField()),
                ('lat', models.FloatField()),
                ('address', models.CharField(blank=True, max_length=500)),
                ('district', models.CharField(blank=True, max_length=100)),
                ('tel', models.CharField(blank=True, max_length=100)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'gis_poi',
                'indexes': [models.Index(fields=['poi_type'], name='gis_poi_poi_typ_0a01fe_idx'), models.Index(fields=['district'], name='gis_poi_distric_4b0189_idx'), models.Index(fields=['lng', 'lat'], name='gis_poi_lng_7b97d2_idx')],
            },
        ),
        migrations.CreateModel(
            name='RoadSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('surface_type', models.CharField(choices=[('plastic_track', '塑胶跑道'), ('dirt_trail', '土路'), ('asphalt', '汥青公路'), ('concrete', '水泥路'), ('mountain_trail', '山路'), ('park_path', '公园步行道'), ('boardwalk', '木栈道'), ('beach', '沙滩')], max_length=50)),
                ('path_geojson', models.JSONField()),
                ('district', models.CharField(blank=True, max_length=100)),
                ('length_m', models.FloatField(default=0)),
                ('avg_slope', models.FloatField(default=0, help_text='平均坡度百分比')),
                ('shade_level', models.IntegerField(default=0, help_text='遮荫等级 0-5')),
                ('has_sea_view', models.BooleanField(default=False)),
                ('elevation_data', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'gis_road_segment',
                'indexes': [models.Index(fields=['surface_type'], name='gis_road_se_surface_060e55_idx'), models.Index(fields=['district'], name='gis_road_se_distric_a6a6d4_idx')],
            },
        ),
    ]
