# Generated by Django 5.2.13 on 2026-04-20 08:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgentSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('user_id', models.CharField(db_index=True, max_length=100)),
                ('current_intent', models.JSONField(blank=True, default=dict, help_text='当前累积的用户意图')),
                ('clarification_history', models.JSONField(blank=True, default=list, help_text='追问与澄清历史')),
                ('state', models.CharField(default='idle', help_text='会话状态：idle/gathering/planning/refining/completed', max_length=32)),
                ('turn_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'agent_session',
            },
        ),
        migrations.CreateModel(
            name='KnowledgeDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_id', models.CharField(db_index=True, max_length=128, unique=True)),
                ('category', models.CharField(db_index=True, help_text='分类：poi/road/scenic/green/sports_medicine/xiamen_knowledge', max_length=64)),
                ('title', models.CharField(max_length=256)),
                ('content', models.TextField(help_text='文本内容')),
                ('embedding', models.JSONField(default=list, help_text='向量嵌入（list of float）')),
                ('source_type', models.CharField(default='database', help_text='来源：database/manual/crawled', max_length=64)),
                ('source_id', models.CharField(blank=True, default='', max_length=128)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'knowledge_document',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeGraphNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_id', models.CharField(db_index=True, max_length=128, unique=True)),
                ('node_type', models.CharField(db_index=True, help_text='类型：poi/road/scenic/green/district/surface_type/sport_type', max_length=64)),
                ('name', models.CharField(max_length=256)),
                ('properties', models.JSONField(blank=True, default=dict)),
                ('lng', models.FloatField(blank=True, null=True)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'knowledge_graph_node',
                'ordering': ['node_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='LongTermMemory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(db_index=True, max_length=100)),
                ('memory_type', models.CharField(choices=[('preference', '用户偏好'), ('habit', '运动习惯'), ('route_history', '路线历史'), ('feedback', '用户反馈'), ('context', '上下文摘要')], db_index=True, max_length=32)),
                ('key', models.CharField(help_text='记忆键，如 preferred_distance / last_route', max_length=256)),
                ('value', models.TextField(help_text='记忆值')),
                ('importance', models.FloatField(default=0.5, help_text='重要性权重 0-1')),
                ('access_count', models.IntegerField(default=0)),
                ('last_accessed', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'long_term_memory',
                'ordering': ['-importance', '-last_accessed'],
                'unique_together': {('user_id', 'memory_type', 'key')},
            },
        ),
        migrations.CreateModel(
            name='KnowledgeGraphEdge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation', models.CharField(db_index=True, help_text='关系类型：located_in/has_surface/near_by/connects_to/provides/overlooks', max_length=128)),
                ('weight', models.FloatField(default=1.0)),
                ('properties', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_edges', to='smart_engine.knowledgegraphnode')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_edges', to='smart_engine.knowledgegraphnode')),
            ],
            options={
                'db_table': 'knowledge_graph_edge',
                'unique_together': {('source', 'target', 'relation')},
            },
        ),
    ]
