# Generated by Django 5.2.1 on 2026-03-01 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RouteHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_query', models.TextField(verbose_name='用户输入')),
                ('parsed_params', models.JSONField(blank=True, null=True, verbose_name='解析参数')),
                ('routes_count', models.IntegerField(default=0, verbose_name='生成路线数')),
                ('recommended_route', models.CharField(blank=True, max_length=50, verbose_name='推荐路线ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('total_time_s', models.FloatField(blank=True, null=True, verbose_name='总耗时(秒)')),
            ],
            options={
                'verbose_name': '路线历史',
                'verbose_name_plural': '路线历史',
                'ordering': ['-created_at'],
            },
        ),
    ]
